### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by thiagoelg** [thiagoelg/mc853#11]
- [x] Terminar sistema de upload de arquivos / Model de File (WIP @thiagoelg)
- [x] Servir esses arquivos (WIP @thiagoelg)
- [x] Adicionar imagem ao perfil do usário (WIP @thiagoelg)
- [x] Ícones para itens do menu
- [x] Formulário de criação de solicitação (WIP @fellipecaetano)
- [x] Listagem de solicitações (WIP @fellipecaetano)
- [ ] Formulário de resposta de solicitações (WIP @fellipecaetano)
- [ ] Atribuir solicitação a um usuário arbitrário
- [ ] Formulário de avaliação de atendimento
- [ ] Campo de upload de arquivo para forms (Utilizar o File, só armazenar o id do arquivo)
- [x] Listagem de ResponseTypes (vai ser utilizado no formulário de criação de Forms)
- [x] Formulário para criação de forms
- [x] Listagem de forms
- [x] ~~Formulário para criação de ResponseTypes~~
